### PR TITLE
Feature abstract interface

### PR DESCRIPTION
**Pull request by elsavira**
The Abstract interface is completed in accordance with the guidelines set upon the feature. See: https://trello.com/c/cK4tSzWV/15-vs1-abstract-interface1

### CODE REVIEW

**Comment by renskekuip1** [comment]
The print is not correct with the VS in trello. Should print a position.

**Review by renskekuip1 — CHANGES_REQUESTED** [review]
Print is not correct. It should print a position.

**Comment by elsavira** [comment]
Updated feature now, re-review.

**Review by renskekuip1 — APPROVED** [review]
Seems fine like this.

**Pull request merged**
